### ISSUE TITLE
[隐藏色色]无法正常发送

### ISSUE THREAD

**Issue by CUZNIL** [SmallK111407/earth-k-plugin#10]
![image](https://user-images.githubusercontent.com/76582404/196002929-96712f49-a4c7-4e98-b2f2-d137caa4afb5.png)
如图所示。原因不详

**Comment by CUZNIL** [comment]
![Z`}5SQM)OL71FY$$5~HC$P](https://user-images.githubusercontent.com/76582404/196005028-1a82ae41-9e01-4cac-85e6-3119f0d9cbf0.png)
如上图，后续看了下。。。给的图片链接是个空文件

**Comment by SmallK111407** [comment]
API似乎寄了
