### ISSUE TITLE
海外服务器无法使用网易点歌

### ISSUE THREAD

**Issue by leiji001** [SmallK111407/earth-k-plugin#16]
可以给网易点歌设置网络代理吗？网易限制了海外IP连接

**Comment by leiji001** [comment]
![5a2e2afcf65492c1.png](https://user-images.githubusercontent.com/94916764/199302772-859f9a14-bc4d-40ad-8a35-fd506b512e9f.png)

**Comment by SmallK111407** [comment]
你可以尝试设置代理解决，用clash什么的
