### ISSUE TITLE
二次元的我用不了了

### ISSUE THREAD

**Issue by edvanger** [SmallK111407/earth-k-plugin#26]
机器人报错：接口1：[主人的接口] 连接被服务区拒绝：ECONNREFUSED，请检查端口号或接口是否配置正确、服务器是否开启、服务器防火墙是否放行了对应端口，或尝试使用其他接口

本人小白，请问怎么解决..

**Comment by SmallK111407** [comment]
逆天 接口不知道谁的 然后这个是ap的返回，你在土块提issue

**Comment by edvanger** [comment]
抱歉给你造成了麻烦，目前解决了
