### ISSUE TITLE
点歌失败

### ISSUE THREAD

**Issue by Dongguan-Slaughterhouse** [SmallK111407/earth-k-plugin#27]
如图，输入#听7，#听5机器人没有反应，同时控制台输出一个错误。
![image](https://user-images.githubusercontent.com/90093557/215250213-6a643e25-7caf-4f90-b597-0dff2687c4f9.png)
![image](https://user-images.githubusercontent.com/90093557/215250230-5f88dbbb-8bdd-4707-a4b3-5fe56962b557.png)
![image](https://user-images.githubusercontent.com/90093557/215250236-d5637f10-d864-4cf9-83d7-9f6f567a9b76.png)
![image](https://user-images.githubusercontent.com/90093557/215250241-047fdbd2-2f29-4e28-8323-42a487948993.png)

**Comment by Fhm-newbie** [comment]
您好，请问您解决了吗？我也遇到这个情况了，而且昨天晚上刚装上去的时候还能正常点歌
