### ISSUE TITLE
正则误伤问题

### ISSUE THREAD

**Issue by SanQianQVQ** [SmallK111407/earth-k-plugin#28]
https://github.com/SmallK111407/earth-k-plugin/blob/master/apps/NovelAI-Painting.js 中 `#(.*)化(.*)` 会有一定的误伤

**Comment by SanQianQVQ** [comment]
> https://github.com/SmallK111407/earth-k-plugin/blob/master/apps/NovelAI-Painting.js 中 `#(.*)化(.*)` 误伤过大，发送的文字中只要含有化就会被识别，例如化学

**Comment by faithecho** [comment]
同样问题，会与其他插件带化字指令冲突，望解决。

**Comment by 123xuwu** [comment]
我也遇到了

**Comment by SanQianQVQ** [comment]
no response.
