### ISSUE TITLE
练习记忆力没有反应

### ISSUE THREAD

**Issue by pishen12138** [SmallK111407/earth-k-plugin#3]
日志：
[YzBot][16:07:37.763][INFO] recv from: [Group: BOT理发店(584757247), Member: 无
处安放的记忆�(1915395943)] #练习记忆力
[YzBot][16:07:37.788][MARK] [练习记忆力][jyl][BOT理发店(无处安放的记忆�)] #练习
记忆力
生成的随机数：796,30,23,210,319,341,794,324,114,256,
生成的随机数：125,724,535,300,263,668,360,688,486,11,
[YzBot][16:07:38.164][MARK] [图片生成][123][6次] 36.67kb 369ms
[YzBot][16:07:39.236][INFO] succeed to send: [Group(584757247)] [图片]
[YzBot][16:07:39.597][INFO] succeed to send: [Group(584757247)] 请观察下面数字10
秒
g,c,f,h,e,b,d,a,i,
[YzBot][16:07:41.329][MARK] [图片生成][123][7次] 33.79kb 532ms
生成的随机数：4
[YzBot][16:07:41.338][MARK] [练习记忆力][jyl] #练习记忆力 处理完成 3547ms
[YzBot][16:07:41.756][INFO] succeed to send: [Group(584757247)] 请问4是哪个字母
[YzBot][16:07:42.334][INFO] succeed to send: [Group(584757247)] [图片]
[YzBot][16:07:57.449][INFO] recv from: [Group: BOT理发店(584757247), Member: 无
处安放的记忆�(1915395943)] 我猜h
[YzBot][16:07:57.456][MARK] [练习记忆力][wc][BOT理发店(无处安放的记忆�)] 我猜h
无处安放的记忆�
h
4
[
  'g', 'c', 'f', 'h',
  'e', 'b', 'd', 'a',
  'i', ''
]
[YzBot][16:07:57.468][MARK] [练习记忆力][wc] 我猜h 处理完成 0ms

到这就没有反应了

**Comment by SmallK111407** [comment]
#土块更新
