### ISSUE TITLE
猜语音音频转码到amr失败

### ISSUE THREAD

**Issue by ksweb2** [SmallK111407/earth-k-plugin#5]
大佬我这ffmpeg环境也配置了啊，他还是显示这个
![image](https://user-images.githubusercontent.com/100368718/194540766-0dfea460-ce48-4d63-ad65-17bc1ba045f8.png)

**Comment by SmallK111407** [comment]
更新ffmpeg版本，或检查变量配置是否正确，再不行可以尝试重启服务器等

**Comment by ksweb2** [comment]
好的谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月7日(周五) 晚上10:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SmallK111407/earth-k-plugin] 猜语音音频转码到amr失败 (Issue #5)




 
更新ffmpeg版本，或检查变量配置是否正确，再不行可以尝试重启服务器等
