### ISSUE TITLE
画图功能太长的代码是不是暂时没办法处理？

### ISSUE THREAD

**Issue by 1776304537** [SmallK111407/earth-k-plugin#7]
![QQ截图20221015003127](https://user-images.githubusercontent.com/24807330/195896250-0ee9eb76-481e-4051-a94e-9f2f97aa6874.jpg)
![QQ截图20221015003139](https://user-images.githubusercontent.com/24807330/195896262-078db055-7f91-4ad1-808b-8bc6b99b1cfe.jpg)
直接不回复了

**Comment by SmallK111407** [comment]
画图功能API似乎跑路了
