### ISSUE TITLE
api接口问题

### ISSUE THREAD

**Issue by xueqi5201314** [SmallK111407/earth-k-plugin#9]
隐藏的sese功能的api是不是出了问题，图片看不到

**Comment by SmallK111407** [comment]
必须是主人且私聊使用

**Comment by xueqi5201314** [comment]
我是私聊使用的，但是他图片过来就是感叹号，
![image](https://user-images.githubusercontent.com/108047693/196023841-1714c371-8368-4c84-bbd7-d08b1459e4ef.png)
